version: "3.3"
services:
  postgres:
    image: postgres:12
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - app-network
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=[postgres username] #edit
      - POSTGRES_PASSWORD=[postgres password] #edit
      - POSTGRES_DB=[database name]#edit
      - LC_ALL=C.UTF-8 #edit
      - APP_DB_USER=[database user name] #edit
      - APP_DB_PASS=[postgres user password] #edit
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: [pgadmin email] #edit
      PGADMIN_DEFAULT_PASSWORD: [pgadmin password] #edit
    ports:
      - "80:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - app-network
volumes:
  postgres_data:
  pgadmin:
networks:
  app-network:
    driver: bridge

